version: "3.8"
services:
    db:
        image: mysql:8.2.0
        ports: 
            - 3307:3306
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: root 
        # volumes:
        #     - db_persistence:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:5.2.1
        ports:
            - 82:80
# volumes:
#     db_persistence: