GET http://localhost:8081/api

###

GET http://localhost:8081/api/addresses

###

GET http://localhost:8081/api/libraries

###

POST http://localhost:8081/api/addresses
Content-Type: application/json

{
  "location": "addressA"
}

###

# create library with address set to null
POST http://localhost:8081/api/libraries
Content-Type: application/json

{
  "name": "libraryA",
  "address": "http://localhost:8081/api/addresses/1"
}

###

GET http://localhost:8081/api/addresses/1

###

GET http://localhost:8081/api/libraries/1

###

PUT http://localhost:8081/api/libraries/1/address
Content-Type:text/uri-list

http://localhost:8081/api/addresses/1

###

GET http://localhost:8081/api/libraries/1/address

###

DELETE http://localhost:8081/api/libraries/1/address

###

GET http://localhost:8081/api/addresses/1/library

###

GET http://localhost:8081/api/books

###

POST http://localhost:8081/api/books
Content-Type: application/json

{
  "title": "bookA"
}

###

GET http://localhost:8081/api/books/1

###

PUT http://localhost:8081/api/books/1/library
Content-Type:text/uri-list

http://localhost:8081/api/libraries/1

###

GET http://localhost:8081/api/books/1/library

###

GET http://localhost:8081/api/libraries/1/books

###

GET http://localhost:8081/api/authors

###

POST http://localhost:8081/api/authors
Content-Type: application/json

{
  "name": "authorA"
}

###

GET http://localhost:8081/api/authors/1

###

PUT http://localhost:8081/api/authors/1/books
Content-Type:text/uri-list

http://localhost:8081/api/books/1

###

GET http://localhost:8081/api/authors/1/books

###
GET http://localhost:8081/api/books/1/authors
